name: Publish

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox-gh-actions wheel twine
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
      - name: Build source and wheel package
        run: |
          python -m pip install --upgrade build
          python -m build
      - name: Check packages
        run: |
          twine check dist/*
      - name: Publish package
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
